# linux modules overlay/br_netfilter
- name: "Copy modules conf"
  ansible.builtin.template:
    src: templates/modules-load.d/k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
  become: true
  register: copy_modules_conf

- name: "Load common modules"
  ansible.builtin.command:
    cmd: "modprobe {{ item }}"
  become: true
  loop: "{{ kubernetes_common_linux_modules }}"
  when: copy_modules_conf is changed

- name: "Copy sysctl config"
  ansible.builtin.copy:
    src: files/sysctl.d/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  become: true
  register: copy_sysctl_config

- name: "Apply sysctl conf"
  ansible.builtin.command:
    cmd: sysctl --system
  become: true
  when: copy_sysctl_config is changed

- name: "Add controlplane address to /etc/hosts"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "cluster-endpoint"
    line: "{{kubernetes_common_controlplane_ip}} cluster-endpoint"
    owner: root
    group: root
    mode: '0644'
  become: true
