- name: Bootstrap controlplane
  ansible.builtin.command:
    cmd: "kubeadm init --control-plane-endpoint=cluster-endpoint --pod-network-cidr='{{kubernetes_controlplane_pod_network_cidr}}' --service-cidr='{{kubernetes_controlplane_service_cidr}}'"
    creates: /etc/kubernetes/kubelet.conf
  become: true

- name: Create token
  ansible.builtin.command:
    cmd: "kubeadm token create"
  become: true
  register: kubeadm_join_token

- name: Get CA certificate hash
  community.crypto.x509_certificate_info:
    path: /etc/kubernetes/pki/ca.crt
  register: kubeadm_join_ca_hash

- name: Fetch join command
  local_action:
    module: ansible.builtin.copy
    content: 'kubeadm join cluster-endpoint:6443 --token {{ kubeadm_join_token.stdout }} --discovery-token-ca-cert-hash sha256:{{ kubeadm_join_ca_hash.public_key_fingerprints.sha256 | replace(":","") }}'
    dest: ./.credentials/join_command
    force: false # avoid copying the file if it already exists
  run_once: true

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    mode: '0700'
    owner: ubuntu
    group: ubuntu
    state: directory

- name: Copy kubeconfig to ubuntu user
  ansible.builtin.copy:
    dest: /home/ubuntu/.kube/config
    src: /etc/kubernetes/admin.conf
    mode: preserve
    owner: ubuntu
    group: ubuntu
    remote_src: true
  become: true

- name: Install Kubernetes Network add-on
  ansible.builtin.command:
    cmd: "kubectl apply -f {{kubernetes_controlplane_network_addon_manifest}}"
    creates: "{{kubernetes_common_ansible_directory}}/install_kubernetes_network_add_on.lock"
  register: install_kubernetes_network_add_on

- name: Create install_kubernetes_network_add_on.lock
  ansible.builtin.command:
    cmd: "touch {{kubernetes_common_ansible_directory}}/install_kubernetes_network_add_on.lock"
    creates: "{{kubernetes_common_ansible_directory}}/install_kubernetes_network_add_on.lock"
  when: install_kubernetes_network_add_on is changed
