# containerd tasks
- name: "Download containerd v{{common_containerd_version}}"
  ansible.builtin.get_url:
    dest: "{{common_ansible_directory}}/{{common_containerd_tar}}"
    url: "https://github.com/containerd/containerd/releases/download/v{{common_containerd_version}}/{{common_containerd_tar}}"
  register: containerd_download

- name: "Extract containerd"
  ansible.builtin.unarchive:
    src: "{{common_ansible_directory}}/{{common_containerd_tar}}"
    creates: /usr/local/bin/containerd
    dest: /usr/local
    remote_src: yes
  become: true
  register: containerd_extracted
  when: containerd_download is changed

- name: "Copy containerd.service"
  ansible.builtin.copy:
    src: files/containerd.service
    dest: /lib/systemd/system/containerd.service
  register: containerd_unit_file_copy
  become: true

- name: "Enable containerd service"
  ansible.builtin.systemd_service:
    name: containerd.service
    daemon_reload: true
    state: started
    enabled: true
  become: true

# runc tasks
- name: "Install runc v{{common_runc_version}}"
  ansible.builtin.get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v{{common_runc_version}}/runc.amd64"
    dest: /usr/local/sbin/runc
    mode: 0755
  register: install_runc
  become: true

# cni plugins
- name: Create directory /opt/cni/bin
  ansible.builtin.file:
    path: "/opt/cni/bin"
    state: directory
    owner: "root"
    mode: 0755
  become: true

- name: "Install cni-plugins v{{common_cni_plugins_version}}"
  ansible.builtin.unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/v{{common_cni_plugins_version}}/cni-plugins-linux-amd64-v{{common_cni_plugins_version}}.tgz"
    creates: /opt/cni/bin/bridge
    dest: /opt/cni/bin/
    remote_src: yes
  become: true
  register: cni_plugins_installed

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    mode: 0755
  become: true

- name: Copy containerd config file
  ansible.builtin.copy:
    src: files/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    mode: 0644
  become: true
  notify: "Restart containerd service"
