- name: Create .ansible directory
  ansible.builtin.file:
    path: "{{common_ansible_directory}}"
    state: directory
    owner: "{{ansible_user_id}}"

- include_tasks: linux.yml

- include_tasks: containerd.yml

- include_tasks: k8s.yml
